name: Run PowerShell Script

on: [workflow_dispatch]

jobs:
  run-script:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    - name: Set up PowerShell
      uses: actions/setup-python@v4.6.0
      with:
        python-version: '3.x'

    - name: Check contents
      run: |
        dir

    - name: Run PowerShell script
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pwsh -File deploy-environments-secrets-vars.ps1